// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"podgen/internal/app/podgen/podcast"
	"podgen/internal/app/podgen/proc"
	"sync"
)

// Ensure, that EpisodeStoreMock does implement proc.EpisodeStore.
// If this is not the case, regenerate this file with moq.
var _ proc.EpisodeStore = &EpisodeStoreMock{}

// EpisodeStoreMock is a mock implementation of proc.EpisodeStore.
//
//	func TestSomethingThatUsesEpisodeStore(t *testing.T) {
//
//		// make and configure a mocked proc.EpisodeStore
//		mockedEpisodeStore := &EpisodeStoreMock{
//			FindEpisodesBySessionFunc: func(podcastID string, session string) ([]*podcast.Episode, error) {
//				panic("mock out the FindEpisodesBySession method")
//			},
//			FindEpisodesBySizeLimitFunc: func(podcastID string, status podcast.Status, sizeLimit int64) ([]*podcast.Episode, error) {
//				panic("mock out the FindEpisodesBySizeLimit method")
//			},
//			FindEpisodesByStatusFunc: func(podcastID string, status podcast.Status) ([]*podcast.Episode, error) {
//				panic("mock out the FindEpisodesByStatus method")
//			},
//			GetEpisodeByFilenameFunc: func(podcastID string, fileName string) (*podcast.Episode, error) {
//				panic("mock out the GetEpisodeByFilename method")
//			},
//			GetLastEpisodeByNotStatusFunc: func(podcastID string, status podcast.Status) (*podcast.Episode, error) {
//				panic("mock out the GetLastEpisodeByNotStatus method")
//			},
//			SaveEpisodeFunc: func(podcastID string, episode *podcast.Episode) error {
//				panic("mock out the SaveEpisode method")
//			},
//		}
//
//		// use mockedEpisodeStore in code that requires proc.EpisodeStore
//		// and then make assertions.
//
//	}
type EpisodeStoreMock struct {
	// FindEpisodesBySessionFunc mocks the FindEpisodesBySession method.
	FindEpisodesBySessionFunc func(podcastID string, session string) ([]*podcast.Episode, error)

	// FindEpisodesBySizeLimitFunc mocks the FindEpisodesBySizeLimit method.
	FindEpisodesBySizeLimitFunc func(podcastID string, status podcast.Status, sizeLimit int64) ([]*podcast.Episode, error)

	// FindEpisodesByStatusFunc mocks the FindEpisodesByStatus method.
	FindEpisodesByStatusFunc func(podcastID string, status podcast.Status) ([]*podcast.Episode, error)

	// GetEpisodeByFilenameFunc mocks the GetEpisodeByFilename method.
	GetEpisodeByFilenameFunc func(podcastID string, fileName string) (*podcast.Episode, error)

	// GetLastEpisodeByNotStatusFunc mocks the GetLastEpisodeByNotStatus method.
	GetLastEpisodeByNotStatusFunc func(podcastID string, status podcast.Status) (*podcast.Episode, error)

	// SaveEpisodeFunc mocks the SaveEpisode method.
	SaveEpisodeFunc func(podcastID string, episode *podcast.Episode) error

	// calls tracks calls to the methods.
	calls struct {
		// FindEpisodesBySession holds details about calls to the FindEpisodesBySession method.
		FindEpisodesBySession []struct {
			// PodcastID is the podcastID argument value.
			PodcastID string
			// Session is the session argument value.
			Session string
		}
		// FindEpisodesBySizeLimit holds details about calls to the FindEpisodesBySizeLimit method.
		FindEpisodesBySizeLimit []struct {
			// PodcastID is the podcastID argument value.
			PodcastID string
			// Status is the status argument value.
			Status podcast.Status
			// SizeLimit is the sizeLimit argument value.
			SizeLimit int64
		}
		// FindEpisodesByStatus holds details about calls to the FindEpisodesByStatus method.
		FindEpisodesByStatus []struct {
			// PodcastID is the podcastID argument value.
			PodcastID string
			// Status is the status argument value.
			Status podcast.Status
		}
		// GetEpisodeByFilename holds details about calls to the GetEpisodeByFilename method.
		GetEpisodeByFilename []struct {
			// PodcastID is the podcastID argument value.
			PodcastID string
			// FileName is the fileName argument value.
			FileName string
		}
		// GetLastEpisodeByNotStatus holds details about calls to the GetLastEpisodeByNotStatus method.
		GetLastEpisodeByNotStatus []struct {
			// PodcastID is the podcastID argument value.
			PodcastID string
			// Status is the status argument value.
			Status podcast.Status
		}
		// SaveEpisode holds details about calls to the SaveEpisode method.
		SaveEpisode []struct {
			// PodcastID is the podcastID argument value.
			PodcastID string
			// Episode is the episode argument value.
			Episode *podcast.Episode
		}
	}
	lockFindEpisodesBySession     sync.RWMutex
	lockFindEpisodesBySizeLimit   sync.RWMutex
	lockFindEpisodesByStatus      sync.RWMutex
	lockGetEpisodeByFilename      sync.RWMutex
	lockGetLastEpisodeByNotStatus sync.RWMutex
	lockSaveEpisode               sync.RWMutex
}

// FindEpisodesBySession calls FindEpisodesBySessionFunc.
func (mock *EpisodeStoreMock) FindEpisodesBySession(podcastID string, session string) ([]*podcast.Episode, error) {
	if mock.FindEpisodesBySessionFunc == nil {
		panic("EpisodeStoreMock.FindEpisodesBySessionFunc: method is nil but EpisodeStore.FindEpisodesBySession was just called")
	}
	callInfo := struct {
		PodcastID string
		Session   string
	}{
		PodcastID: podcastID,
		Session:   session,
	}
	mock.lockFindEpisodesBySession.Lock()
	mock.calls.FindEpisodesBySession = append(mock.calls.FindEpisodesBySession, callInfo)
	mock.lockFindEpisodesBySession.Unlock()
	return mock.FindEpisodesBySessionFunc(podcastID, session)
}

// FindEpisodesBySessionCalls gets all the calls that were made to FindEpisodesBySession.
// Check the length with:
//
//	len(mockedEpisodeStore.FindEpisodesBySessionCalls())
func (mock *EpisodeStoreMock) FindEpisodesBySessionCalls() []struct {
	PodcastID string
	Session   string
} {
	var calls []struct {
		PodcastID string
		Session   string
	}
	mock.lockFindEpisodesBySession.RLock()
	calls = mock.calls.FindEpisodesBySession
	mock.lockFindEpisodesBySession.RUnlock()
	return calls
}

// FindEpisodesBySizeLimit calls FindEpisodesBySizeLimitFunc.
func (mock *EpisodeStoreMock) FindEpisodesBySizeLimit(podcastID string, status podcast.Status, sizeLimit int64) ([]*podcast.Episode, error) {
	if mock.FindEpisodesBySizeLimitFunc == nil {
		panic("EpisodeStoreMock.FindEpisodesBySizeLimitFunc: method is nil but EpisodeStore.FindEpisodesBySizeLimit was just called")
	}
	callInfo := struct {
		PodcastID string
		Status    podcast.Status
		SizeLimit int64
	}{
		PodcastID: podcastID,
		Status:    status,
		SizeLimit: sizeLimit,
	}
	mock.lockFindEpisodesBySizeLimit.Lock()
	mock.calls.FindEpisodesBySizeLimit = append(mock.calls.FindEpisodesBySizeLimit, callInfo)
	mock.lockFindEpisodesBySizeLimit.Unlock()
	return mock.FindEpisodesBySizeLimitFunc(podcastID, status, sizeLimit)
}

// FindEpisodesBySizeLimitCalls gets all the calls that were made to FindEpisodesBySizeLimit.
// Check the length with:
//
//	len(mockedEpisodeStore.FindEpisodesBySizeLimitCalls())
func (mock *EpisodeStoreMock) FindEpisodesBySizeLimitCalls() []struct {
	PodcastID string
	Status    podcast.Status
	SizeLimit int64
} {
	var calls []struct {
		PodcastID string
		Status    podcast.Status
		SizeLimit int64
	}
	mock.lockFindEpisodesBySizeLimit.RLock()
	calls = mock.calls.FindEpisodesBySizeLimit
	mock.lockFindEpisodesBySizeLimit.RUnlock()
	return calls
}

// FindEpisodesByStatus calls FindEpisodesByStatusFunc.
func (mock *EpisodeStoreMock) FindEpisodesByStatus(podcastID string, status podcast.Status) ([]*podcast.Episode, error) {
	if mock.FindEpisodesByStatusFunc == nil {
		panic("EpisodeStoreMock.FindEpisodesByStatusFunc: method is nil but EpisodeStore.FindEpisodesByStatus was just called")
	}
	callInfo := struct {
		PodcastID string
		Status    podcast.Status
	}{
		PodcastID: podcastID,
		Status:    status,
	}
	mock.lockFindEpisodesByStatus.Lock()
	mock.calls.FindEpisodesByStatus = append(mock.calls.FindEpisodesByStatus, callInfo)
	mock.lockFindEpisodesByStatus.Unlock()
	return mock.FindEpisodesByStatusFunc(podcastID, status)
}

// FindEpisodesByStatusCalls gets all the calls that were made to FindEpisodesByStatus.
// Check the length with:
//
//	len(mockedEpisodeStore.FindEpisodesByStatusCalls())
func (mock *EpisodeStoreMock) FindEpisodesByStatusCalls() []struct {
	PodcastID string
	Status    podcast.Status
} {
	var calls []struct {
		PodcastID string
		Status    podcast.Status
	}
	mock.lockFindEpisodesByStatus.RLock()
	calls = mock.calls.FindEpisodesByStatus
	mock.lockFindEpisodesByStatus.RUnlock()
	return calls
}

// GetEpisodeByFilename calls GetEpisodeByFilenameFunc.
func (mock *EpisodeStoreMock) GetEpisodeByFilename(podcastID string, fileName string) (*podcast.Episode, error) {
	if mock.GetEpisodeByFilenameFunc == nil {
		panic("EpisodeStoreMock.GetEpisodeByFilenameFunc: method is nil but EpisodeStore.GetEpisodeByFilename was just called")
	}
	callInfo := struct {
		PodcastID string
		FileName  string
	}{
		PodcastID: podcastID,
		FileName:  fileName,
	}
	mock.lockGetEpisodeByFilename.Lock()
	mock.calls.GetEpisodeByFilename = append(mock.calls.GetEpisodeByFilename, callInfo)
	mock.lockGetEpisodeByFilename.Unlock()
	return mock.GetEpisodeByFilenameFunc(podcastID, fileName)
}

// GetEpisodeByFilenameCalls gets all the calls that were made to GetEpisodeByFilename.
// Check the length with:
//
//	len(mockedEpisodeStore.GetEpisodeByFilenameCalls())
func (mock *EpisodeStoreMock) GetEpisodeByFilenameCalls() []struct {
	PodcastID string
	FileName  string
} {
	var calls []struct {
		PodcastID string
		FileName  string
	}
	mock.lockGetEpisodeByFilename.RLock()
	calls = mock.calls.GetEpisodeByFilename
	mock.lockGetEpisodeByFilename.RUnlock()
	return calls
}

// GetLastEpisodeByNotStatus calls GetLastEpisodeByNotStatusFunc.
func (mock *EpisodeStoreMock) GetLastEpisodeByNotStatus(podcastID string, status podcast.Status) (*podcast.Episode, error) {
	if mock.GetLastEpisodeByNotStatusFunc == nil {
		panic("EpisodeStoreMock.GetLastEpisodeByNotStatusFunc: method is nil but EpisodeStore.GetLastEpisodeByNotStatus was just called")
	}
	callInfo := struct {
		PodcastID string
		Status    podcast.Status
	}{
		PodcastID: podcastID,
		Status:    status,
	}
	mock.lockGetLastEpisodeByNotStatus.Lock()
	mock.calls.GetLastEpisodeByNotStatus = append(mock.calls.GetLastEpisodeByNotStatus, callInfo)
	mock.lockGetLastEpisodeByNotStatus.Unlock()
	return mock.GetLastEpisodeByNotStatusFunc(podcastID, status)
}

// GetLastEpisodeByNotStatusCalls gets all the calls that were made to GetLastEpisodeByNotStatus.
// Check the length with:
//
//	len(mockedEpisodeStore.GetLastEpisodeByNotStatusCalls())
func (mock *EpisodeStoreMock) GetLastEpisodeByNotStatusCalls() []struct {
	PodcastID string
	Status    podcast.Status
} {
	var calls []struct {
		PodcastID string
		Status    podcast.Status
	}
	mock.lockGetLastEpisodeByNotStatus.RLock()
	calls = mock.calls.GetLastEpisodeByNotStatus
	mock.lockGetLastEpisodeByNotStatus.RUnlock()
	return calls
}

// SaveEpisode calls SaveEpisodeFunc.
func (mock *EpisodeStoreMock) SaveEpisode(podcastID string, episode *podcast.Episode) error {
	if mock.SaveEpisodeFunc == nil {
		panic("EpisodeStoreMock.SaveEpisodeFunc: method is nil but EpisodeStore.SaveEpisode was just called")
	}
	callInfo := struct {
		PodcastID string
		Episode   *podcast.Episode
	}{
		PodcastID: podcastID,
		Episode:   episode,
	}
	mock.lockSaveEpisode.Lock()
	mock.calls.SaveEpisode = append(mock.calls.SaveEpisode, callInfo)
	mock.lockSaveEpisode.Unlock()
	return mock.SaveEpisodeFunc(podcastID, episode)
}

// SaveEpisodeCalls gets all the calls that were made to SaveEpisode.
// Check the length with:
//
//	len(mockedEpisodeStore.SaveEpisodeCalls())
func (mock *EpisodeStoreMock) SaveEpisodeCalls() []struct {
	PodcastID string
	Episode   *podcast.Episode
} {
	var calls []struct {
		PodcastID string
		Episode   *podcast.Episode
	}
	mock.lockSaveEpisode.RLock()
	calls = mock.calls.SaveEpisode
	mock.lockSaveEpisode.RUnlock()
	return calls
}
