// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"podgen/internal/app/podgen/podcast"
	"podgen/internal/app/podgen/proc"
	"sync"
)

// Ensure, that FileScannerMock does implement proc.FileScanner.
// If this is not the case, regenerate this file with moq.
var _ proc.FileScanner = &FileScannerMock{}

// FileScannerMock is a mock implementation of proc.FileScanner.
//
//	func TestSomethingThatUsesFileScanner(t *testing.T) {
//
//		// make and configure a mocked proc.FileScanner
//		mockedFileScanner := &FileScannerMock{
//			FindEpisodesFunc: func(folderName string) ([]*podcast.Episode, error) {
//				panic("mock out the FindEpisodes method")
//			},
//		}
//
//		// use mockedFileScanner in code that requires proc.FileScanner
//		// and then make assertions.
//
//	}
type FileScannerMock struct {
	// FindEpisodesFunc mocks the FindEpisodes method.
	FindEpisodesFunc func(folderName string) ([]*podcast.Episode, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindEpisodes holds details about calls to the FindEpisodes method.
		FindEpisodes []struct {
			// FolderName is the folderName argument value.
			FolderName string
		}
	}
	lockFindEpisodes sync.RWMutex
}

// FindEpisodes calls FindEpisodesFunc.
func (mock *FileScannerMock) FindEpisodes(folderName string) ([]*podcast.Episode, error) {
	if mock.FindEpisodesFunc == nil {
		panic("FileScannerMock.FindEpisodesFunc: method is nil but FileScanner.FindEpisodes was just called")
	}
	callInfo := struct {
		FolderName string
	}{
		FolderName: folderName,
	}
	mock.lockFindEpisodes.Lock()
	mock.calls.FindEpisodes = append(mock.calls.FindEpisodes, callInfo)
	mock.lockFindEpisodes.Unlock()
	return mock.FindEpisodesFunc(folderName)
}

// FindEpisodesCalls gets all the calls that were made to FindEpisodes.
// Check the length with:
//
//	len(mockedFileScanner.FindEpisodesCalls())
func (mock *FileScannerMock) FindEpisodesCalls() []struct {
	FolderName string
} {
	var calls []struct {
		FolderName string
	}
	mock.lockFindEpisodes.RLock()
	calls = mock.calls.FindEpisodes
	mock.lockFindEpisodes.RUnlock()
	return calls
}
