// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"podgen/internal/app/podgen/proc"
	"sync"
)

// Ensure, that ObjectStorageMock does implement proc.ObjectStorage.
// If this is not the case, regenerate this file with moq.
var _ proc.ObjectStorage = &ObjectStorageMock{}

// ObjectStorageMock is a mock implementation of proc.ObjectStorage.
//
//	func TestSomethingThatUsesObjectStorage(t *testing.T) {
//
//		// make and configure a mocked proc.ObjectStorage
//		mockedObjectStorage := &ObjectStorageMock{
//			DeleteEpisodeFunc: func(ctx context.Context, objectName string) error {
//				panic("mock out the DeleteEpisode method")
//			},
//			GetObjectInfoFunc: func(ctx context.Context, objectName string) (*proc.ObjectInfo, error) {
//				panic("mock out the GetObjectInfo method")
//			},
//			UploadEpisodeFunc: func(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error) {
//				panic("mock out the UploadEpisode method")
//			},
//			UploadFeedFunc: func(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error) {
//				panic("mock out the UploadFeed method")
//			},
//			UploadImageFunc: func(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error) {
//				panic("mock out the UploadImage method")
//			},
//		}
//
//		// use mockedObjectStorage in code that requires proc.ObjectStorage
//		// and then make assertions.
//
//	}
type ObjectStorageMock struct {
	// DeleteEpisodeFunc mocks the DeleteEpisode method.
	DeleteEpisodeFunc func(ctx context.Context, objectName string) error

	// GetObjectInfoFunc mocks the GetObjectInfo method.
	GetObjectInfoFunc func(ctx context.Context, objectName string) (*proc.ObjectInfo, error)

	// UploadEpisodeFunc mocks the UploadEpisode method.
	UploadEpisodeFunc func(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error)

	// UploadFeedFunc mocks the UploadFeed method.
	UploadFeedFunc func(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error)

	// UploadImageFunc mocks the UploadImage method.
	UploadImageFunc func(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteEpisode holds details about calls to the DeleteEpisode method.
		DeleteEpisode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectName is the objectName argument value.
			ObjectName string
		}
		// GetObjectInfo holds details about calls to the GetObjectInfo method.
		GetObjectInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectName is the objectName argument value.
			ObjectName string
		}
		// UploadEpisode holds details about calls to the UploadEpisode method.
		UploadEpisode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectName is the objectName argument value.
			ObjectName string
			// FilePath is the filePath argument value.
			FilePath string
		}
		// UploadFeed holds details about calls to the UploadFeed method.
		UploadFeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectName is the objectName argument value.
			ObjectName string
			// FilePath is the filePath argument value.
			FilePath string
		}
		// UploadImage holds details about calls to the UploadImage method.
		UploadImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectName is the objectName argument value.
			ObjectName string
			// FilePath is the filePath argument value.
			FilePath string
		}
	}
	lockDeleteEpisode sync.RWMutex
	lockGetObjectInfo sync.RWMutex
	lockUploadEpisode sync.RWMutex
	lockUploadFeed    sync.RWMutex
	lockUploadImage   sync.RWMutex
}

// DeleteEpisode calls DeleteEpisodeFunc.
func (mock *ObjectStorageMock) DeleteEpisode(ctx context.Context, objectName string) error {
	if mock.DeleteEpisodeFunc == nil {
		panic("ObjectStorageMock.DeleteEpisodeFunc: method is nil but ObjectStorage.DeleteEpisode was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ObjectName string
	}{
		Ctx:        ctx,
		ObjectName: objectName,
	}
	mock.lockDeleteEpisode.Lock()
	mock.calls.DeleteEpisode = append(mock.calls.DeleteEpisode, callInfo)
	mock.lockDeleteEpisode.Unlock()
	return mock.DeleteEpisodeFunc(ctx, objectName)
}

// DeleteEpisodeCalls gets all the calls that were made to DeleteEpisode.
// Check the length with:
//
//	len(mockedObjectStorage.DeleteEpisodeCalls())
func (mock *ObjectStorageMock) DeleteEpisodeCalls() []struct {
	Ctx        context.Context
	ObjectName string
} {
	var calls []struct {
		Ctx        context.Context
		ObjectName string
	}
	mock.lockDeleteEpisode.RLock()
	calls = mock.calls.DeleteEpisode
	mock.lockDeleteEpisode.RUnlock()
	return calls
}

// GetObjectInfo calls GetObjectInfoFunc.
func (mock *ObjectStorageMock) GetObjectInfo(ctx context.Context, objectName string) (*proc.ObjectInfo, error) {
	if mock.GetObjectInfoFunc == nil {
		panic("ObjectStorageMock.GetObjectInfoFunc: method is nil but ObjectStorage.GetObjectInfo was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ObjectName string
	}{
		Ctx:        ctx,
		ObjectName: objectName,
	}
	mock.lockGetObjectInfo.Lock()
	mock.calls.GetObjectInfo = append(mock.calls.GetObjectInfo, callInfo)
	mock.lockGetObjectInfo.Unlock()
	return mock.GetObjectInfoFunc(ctx, objectName)
}

// GetObjectInfoCalls gets all the calls that were made to GetObjectInfo.
// Check the length with:
//
//	len(mockedObjectStorage.GetObjectInfoCalls())
func (mock *ObjectStorageMock) GetObjectInfoCalls() []struct {
	Ctx        context.Context
	ObjectName string
} {
	var calls []struct {
		Ctx        context.Context
		ObjectName string
	}
	mock.lockGetObjectInfo.RLock()
	calls = mock.calls.GetObjectInfo
	mock.lockGetObjectInfo.RUnlock()
	return calls
}

// UploadEpisode calls UploadEpisodeFunc.
func (mock *ObjectStorageMock) UploadEpisode(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error) {
	if mock.UploadEpisodeFunc == nil {
		panic("ObjectStorageMock.UploadEpisodeFunc: method is nil but ObjectStorage.UploadEpisode was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ObjectName string
		FilePath   string
	}{
		Ctx:        ctx,
		ObjectName: objectName,
		FilePath:   filePath,
	}
	mock.lockUploadEpisode.Lock()
	mock.calls.UploadEpisode = append(mock.calls.UploadEpisode, callInfo)
	mock.lockUploadEpisode.Unlock()
	return mock.UploadEpisodeFunc(ctx, objectName, filePath)
}

// UploadEpisodeCalls gets all the calls that were made to UploadEpisode.
// Check the length with:
//
//	len(mockedObjectStorage.UploadEpisodeCalls())
func (mock *ObjectStorageMock) UploadEpisodeCalls() []struct {
	Ctx        context.Context
	ObjectName string
	FilePath   string
} {
	var calls []struct {
		Ctx        context.Context
		ObjectName string
		FilePath   string
	}
	mock.lockUploadEpisode.RLock()
	calls = mock.calls.UploadEpisode
	mock.lockUploadEpisode.RUnlock()
	return calls
}

// UploadFeed calls UploadFeedFunc.
func (mock *ObjectStorageMock) UploadFeed(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error) {
	if mock.UploadFeedFunc == nil {
		panic("ObjectStorageMock.UploadFeedFunc: method is nil but ObjectStorage.UploadFeed was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ObjectName string
		FilePath   string
	}{
		Ctx:        ctx,
		ObjectName: objectName,
		FilePath:   filePath,
	}
	mock.lockUploadFeed.Lock()
	mock.calls.UploadFeed = append(mock.calls.UploadFeed, callInfo)
	mock.lockUploadFeed.Unlock()
	return mock.UploadFeedFunc(ctx, objectName, filePath)
}

// UploadFeedCalls gets all the calls that were made to UploadFeed.
// Check the length with:
//
//	len(mockedObjectStorage.UploadFeedCalls())
func (mock *ObjectStorageMock) UploadFeedCalls() []struct {
	Ctx        context.Context
	ObjectName string
	FilePath   string
} {
	var calls []struct {
		Ctx        context.Context
		ObjectName string
		FilePath   string
	}
	mock.lockUploadFeed.RLock()
	calls = mock.calls.UploadFeed
	mock.lockUploadFeed.RUnlock()
	return calls
}

// UploadImage calls UploadImageFunc.
func (mock *ObjectStorageMock) UploadImage(ctx context.Context, objectName string, filePath string) (*proc.UploadResult, error) {
	if mock.UploadImageFunc == nil {
		panic("ObjectStorageMock.UploadImageFunc: method is nil but ObjectStorage.UploadImage was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ObjectName string
		FilePath   string
	}{
		Ctx:        ctx,
		ObjectName: objectName,
		FilePath:   filePath,
	}
	mock.lockUploadImage.Lock()
	mock.calls.UploadImage = append(mock.calls.UploadImage, callInfo)
	mock.lockUploadImage.Unlock()
	return mock.UploadImageFunc(ctx, objectName, filePath)
}

// UploadImageCalls gets all the calls that were made to UploadImage.
// Check the length with:
//
//	len(mockedObjectStorage.UploadImageCalls())
func (mock *ObjectStorageMock) UploadImageCalls() []struct {
	Ctx        context.Context
	ObjectName string
	FilePath   string
} {
	var calls []struct {
		Ctx        context.Context
		ObjectName string
		FilePath   string
	}
	mock.lockUploadImage.RLock()
	calls = mock.calls.UploadImage
	mock.lockUploadImage.RUnlock()
	return calls
}
