// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"podgen/internal/app/podgen/proc"
	"sync"
)

// Ensure, that ProgressReporterMock does implement proc.ProgressReporter.
// If this is not the case, regenerate this file with moq.
var _ proc.ProgressReporter = &ProgressReporterMock{}

// ProgressReporterMock is a mock implementation of proc.ProgressReporter.
//
//	func TestSomethingThatUsesProgressReporter(t *testing.T) {
//
//		// make and configure a mocked proc.ProgressReporter
//		mockedProgressReporter := &ProgressReporterMock{
//			StartFileFunc: func(workerID int, filename string, totalSize int64) {},
//			UpdateProgressFunc: func(workerID int, uploaded int64, total int64) {},
//			CompleteFileFunc: func(workerID int, fileSize int64, err error) {},
//			FinishFunc: func() {},
//		}
//
//		// use mockedProgressReporter in code that requires proc.ProgressReporter
//		// and then make assertions.
//
//	}
type ProgressReporterMock struct {
	// StartFileFunc mocks the StartFile method.
	StartFileFunc func(workerID int, filename string, totalSize int64)

	// UpdateProgressFunc mocks the UpdateProgress method.
	UpdateProgressFunc func(workerID int, uploaded int64, total int64)

	// CompleteFileFunc mocks the CompleteFile method.
	CompleteFileFunc func(workerID int, fileSize int64, err error)

	// FinishFunc mocks the Finish method.
	FinishFunc func()

	// ResetFunc mocks the Reset method.
	ResetFunc func(totalTasks int)

	// calls tracks calls to the methods.
	calls struct {
		// StartFile holds details about calls to the StartFile method.
		StartFile []struct {
			// WorkerID is the workerID argument value.
			WorkerID int
			// Filename is the filename argument value.
			Filename string
			// TotalSize is the totalSize argument value.
			TotalSize int64
		}
		// UpdateProgress holds details about calls to the UpdateProgress method.
		UpdateProgress []struct {
			// WorkerID is the workerID argument value.
			WorkerID int
			// Uploaded is the uploaded argument value.
			Uploaded int64
			// Total is the total argument value.
			Total int64
		}
		// CompleteFile holds details about calls to the CompleteFile method.
		CompleteFile []struct {
			// WorkerID is the workerID argument value.
			WorkerID int
			// FileSize is the fileSize argument value.
			FileSize int64
			// Err is the err argument value.
			Err error
		}
		// Finish holds details about calls to the Finish method.
		Finish []struct{}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
			// TotalTasks is the totalTasks argument value.
			TotalTasks int
		}
	}
	lockStartFile      sync.RWMutex
	lockUpdateProgress sync.RWMutex
	lockCompleteFile   sync.RWMutex
	lockFinish         sync.RWMutex
	lockReset          sync.RWMutex
}

// StartFile calls StartFileFunc.
func (mock *ProgressReporterMock) StartFile(workerID int, filename string, totalSize int64) {
	if mock.StartFileFunc == nil {
		panic("ProgressReporterMock.StartFileFunc: method is nil but ProgressReporter.StartFile was just called")
	}
	callInfo := struct {
		WorkerID  int
		Filename  string
		TotalSize int64
	}{
		WorkerID:  workerID,
		Filename:  filename,
		TotalSize: totalSize,
	}
	mock.lockStartFile.Lock()
	mock.calls.StartFile = append(mock.calls.StartFile, callInfo)
	mock.lockStartFile.Unlock()
	mock.StartFileFunc(workerID, filename, totalSize)
}

// StartFileCalls gets all the calls that were made to StartFile.
func (mock *ProgressReporterMock) StartFileCalls() []struct {
	WorkerID  int
	Filename  string
	TotalSize int64
} {
	var calls []struct {
		WorkerID  int
		Filename  string
		TotalSize int64
	}
	mock.lockStartFile.RLock()
	calls = mock.calls.StartFile
	mock.lockStartFile.RUnlock()
	return calls
}

// UpdateProgress calls UpdateProgressFunc.
func (mock *ProgressReporterMock) UpdateProgress(workerID int, uploaded int64, total int64) {
	if mock.UpdateProgressFunc == nil {
		panic("ProgressReporterMock.UpdateProgressFunc: method is nil but ProgressReporter.UpdateProgress was just called")
	}
	callInfo := struct {
		WorkerID int
		Uploaded int64
		Total    int64
	}{
		WorkerID: workerID,
		Uploaded: uploaded,
		Total:    total,
	}
	mock.lockUpdateProgress.Lock()
	mock.calls.UpdateProgress = append(mock.calls.UpdateProgress, callInfo)
	mock.lockUpdateProgress.Unlock()
	mock.UpdateProgressFunc(workerID, uploaded, total)
}

// UpdateProgressCalls gets all the calls that were made to UpdateProgress.
func (mock *ProgressReporterMock) UpdateProgressCalls() []struct {
	WorkerID int
	Uploaded int64
	Total    int64
} {
	var calls []struct {
		WorkerID int
		Uploaded int64
		Total    int64
	}
	mock.lockUpdateProgress.RLock()
	calls = mock.calls.UpdateProgress
	mock.lockUpdateProgress.RUnlock()
	return calls
}

// CompleteFile calls CompleteFileFunc.
func (mock *ProgressReporterMock) CompleteFile(workerID int, fileSize int64, err error) {
	if mock.CompleteFileFunc == nil {
		panic("ProgressReporterMock.CompleteFileFunc: method is nil but ProgressReporter.CompleteFile was just called")
	}
	callInfo := struct {
		WorkerID int
		FileSize int64
		Err      error
	}{
		WorkerID: workerID,
		FileSize: fileSize,
		Err:      err,
	}
	mock.lockCompleteFile.Lock()
	mock.calls.CompleteFile = append(mock.calls.CompleteFile, callInfo)
	mock.lockCompleteFile.Unlock()
	mock.CompleteFileFunc(workerID, fileSize, err)
}

// CompleteFileCalls gets all the calls that were made to CompleteFile.
func (mock *ProgressReporterMock) CompleteFileCalls() []struct {
	WorkerID int
	FileSize int64
	Err      error
} {
	var calls []struct {
		WorkerID int
		FileSize int64
		Err      error
	}
	mock.lockCompleteFile.RLock()
	calls = mock.calls.CompleteFile
	mock.lockCompleteFile.RUnlock()
	return calls
}

// Finish calls FinishFunc.
func (mock *ProgressReporterMock) Finish() {
	if mock.FinishFunc == nil {
		panic("ProgressReporterMock.FinishFunc: method is nil but ProgressReporter.Finish was just called")
	}
	callInfo := struct{}{}
	mock.lockFinish.Lock()
	mock.calls.Finish = append(mock.calls.Finish, callInfo)
	mock.lockFinish.Unlock()
	mock.FinishFunc()
}

// FinishCalls gets all the calls that were made to Finish.
func (mock *ProgressReporterMock) FinishCalls() []struct{} {
	var calls []struct{}
	mock.lockFinish.RLock()
	calls = mock.calls.Finish
	mock.lockFinish.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *ProgressReporterMock) Reset(totalTasks int) {
	if mock.ResetFunc == nil {
		panic("ProgressReporterMock.ResetFunc: method is nil but ProgressReporter.Reset was just called")
	}
	callInfo := struct {
		TotalTasks int
	}{
		TotalTasks: totalTasks,
	}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	mock.ResetFunc(totalTasks)
}

// ResetCalls gets all the calls that were made to Reset.
func (mock *ProgressReporterMock) ResetCalls() []struct {
	TotalTasks int
} {
	var calls []struct {
		TotalTasks int
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}
